use_frameworks!

platform :ios, '10.0'

target 'SpeechText_Example' do
  pod 'SpeechText', :path => '../'

  target 'SpeechText_Tests' do
    inherit! :search_paths

    pod 'SocketRocket'
    pod 'AFNetworking'
  end
end